base_url : https://training-platform.doppio-tech.com/
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3Rfc2lnbnVwQG1haWwuY29tIiwiaWQiOjEyMjc4fQ.fcxZsFzN4ul4oDYG8hXH0mbl2w9AmlUPJRfVmm7lf3Y
BROWSER : chrome